cc_binary(
    name = "main",
    srcs = [
        "defines.hpp",
        "folder_example/foo.cpp",
        "folder_example/foo.hpp",
        "main.cpp",
        "random.hpp",
        "stopwatch.hpp",
        "utils.hpp",
    ],
)
